/**
 * Espelho do catálogo mínimo do frontend + itens extras para desenvolvimento.
 * Seed idempotente (upsert por code). Importação TUSS em massa: scripts Python
 * (exam-catalog:from-tuss) + scripts/import-exam-catalog-json.ts com DATABASE_URL (sem API).
 */
export const EXAM_CATALOG_SEED_ROWS: Array<{
  code: string;
  name: string;
  type:
    | 'LABORATORY'
    | 'ANATOMOPATHOLOGICAL'
    | 'IMMUNOHISTOCHEMICAL'
    | 'IMAGING';
  specimenDefault?: string | null;
  unit?: string | null;
  referenceRange?: string | null;
  rolItemCode?: string | null;
}> = [
  {
    code: 'HEMO',
    name: 'Hemograma completo',
    type: 'LABORATORY',
    specimenDefault: 'Sangue venoso',
    unit: null,
    referenceRange: null,
  },
  {
    code: 'GASO-A',
    name: 'Gasometria arterial',
    type: 'LABORATORY',
    specimenDefault: 'Sangue arterial',
    unit: null,
    referenceRange: null,
  },
  {
    code: 'GASO-V',
    name: 'Gasometria venosa',
    type: 'LABORATORY',
    specimenDefault: 'Sangue venoso',
    unit: null,
    referenceRange: null,
  },
  {
    code: 'EAS',
    name: 'EAS / Urina tipo 1',
    type: 'LABORATORY',
    specimenDefault: 'Urina simples',
    unit: null,
    referenceRange: null,
  },
  {
    code: 'GLIC',
    name: 'Glicemia de jejum',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'mg/dL',
    referenceRange: '70-99',
  },
  {
    code: 'HBA1C',
    name: 'HbA1c',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: '%',
    referenceRange: '<5,7',
  },
  {
    code: 'CREAT',
    name: 'Creatinina',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'mg/dL',
    referenceRange: '0,7-1,2 (M); 0,6-1,1 (F)',
  },
  {
    code: 'UREIA',
    name: 'Ureia',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'mg/dL',
    referenceRange: '15-45',
  },
  {
    code: 'TGO',
    name: 'TGO (AST)',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'U/L',
    referenceRange: '<40',
  },
  {
    code: 'TGP',
    name: 'TGP (ALT)',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'U/L',
    referenceRange: '<41',
  },
  {
    code: 'BT',
    name: 'Bilirrubina total',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'mg/dL',
    referenceRange: '0,2-1,2',
  },
  {
    code: 'ALB',
    name: 'Albumina',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'g/dL',
    referenceRange: '3,4-5,4',
  },
  {
    code: 'CEA',
    name: 'CEA',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'ng/mL',
    referenceRange: '<5 (não fumantes); <10 (fumantes)',
  },
  {
    code: 'CA199',
    name: 'CA 19-9',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'U/mL',
    referenceRange: '<37',
  },
  {
    code: 'CA125',
    name: 'CA 125',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'U/mL',
    referenceRange: '<35',
  },
  {
    code: 'CA153',
    name: 'CA 15-3',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'U/mL',
    referenceRange: '<25',
  },
  {
    code: 'PSA',
    name: 'PSA total',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'ng/mL',
    referenceRange: '<4',
  },
  {
    code: 'AFP',
    name: 'AFP',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'ng/mL',
    referenceRange: '<10',
  },
  {
    code: 'BHCG',
    name: 'β-HCG',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'mUI/mL',
    referenceRange: 'Ver contexto',
  },
  {
    code: 'LDH',
    name: 'LDH',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'U/L',
    referenceRange: '140-280',
  },
  {
    code: 'FA',
    name: 'Fosfatase alcalina',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'U/L',
    referenceRange: '40-150',
  },
  {
    code: 'GGT',
    name: 'GGT',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'U/L',
    referenceRange: '<60',
  },
  {
    code: 'CA',
    name: 'Cálcio',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'mg/dL',
    referenceRange: '8,6-10,2',
  },
  {
    code: 'NA',
    name: 'Sódio',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'mEq/L',
    referenceRange: '136-145',
  },
  {
    code: 'K',
    name: 'Potássio',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'mEq/L',
    referenceRange: '3,5-5,0',
  },
  {
    code: 'MG',
    name: 'Magnésio',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'mEq/L',
    referenceRange: '1,5-2,5',
  },
  {
    code: 'P',
    name: 'Fósforo',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'mg/dL',
    referenceRange: '2,5-4,5',
  },
  {
    code: 'AU',
    name: 'Ácido úrico',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'mg/dL',
    referenceRange: '3,5-7,2 (M); 2,6-6,0 (F)',
  },
  {
    code: 'HB',
    name: 'Hemoglobina',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'g/dL',
    referenceRange: '13-17 (M); 12-16 (F)',
  },
  {
    code: 'LEUC',
    name: 'Leucócitos',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: '/mm³',
    referenceRange: '4.500-11.000',
  },
  {
    code: 'PLAQ',
    name: 'Plaquetas',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: '/mm³',
    referenceRange: '150.000-400.000',
  },
  {
    code: 'INR',
    name: 'INR',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: '-',
    referenceRange: '0,8-1,2',
  },
  {
    code: 'TSH',
    name: 'TSH',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'mUI/L',
    referenceRange: '0,4-4,0',
  },
  {
    code: 'T4L',
    name: 'T4 livre',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'ng/dL',
    referenceRange: '0,8-1,8',
  },
  {
    code: 'B12',
    name: 'Vitamina B12',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'pg/mL',
    referenceRange: '200-900',
  },
  {
    code: 'FOLATO',
    name: 'Ácido fólico',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'ng/mL',
    referenceRange: '>3',
  },
  {
    code: 'UROCULT',
    name: 'Urocultura',
    type: 'LABORATORY',
    specimenDefault: 'Urina simples',
    unit: '-',
    referenceRange: 'Negativa',
  },
  {
    code: 'PROT24H',
    name: 'Proteinúria 24h',
    type: 'LABORATORY',
    specimenDefault: 'Urina de 24 horas',
    unit: 'mg/24h',
    referenceRange: '<150',
  },
  {
    code: 'CREAT-U',
    name: 'Creatinina urinária',
    type: 'LABORATORY',
    specimenDefault: 'Urina simples',
    unit: 'mg/dL',
    referenceRange: 'Ver contexto',
  },
  {
    code: 'CREAT-24H',
    name: 'Creatinina urina 24h',
    type: 'LABORATORY',
    specimenDefault: 'Urina de 24 horas',
    unit: 'mg/24h',
    referenceRange: 'Ver contexto',
  },
  {
    code: 'CLEARANCE',
    name: 'Clearance de creatinina',
    type: 'LABORATORY',
    specimenDefault: null,
    unit: 'mL/min',
    referenceRange: '>90',
  },
  {
    code: 'BIOPSIA MAMA',
    name: 'Biópsia de mama',
    type: 'ANATOMOPATHOLOGICAL',
    specimenDefault: 'Tecido (biópsia)',
    unit: '-',
    referenceRange: 'Ver laudo',
  },
  {
    code: 'BIOPSIA PROSTATA',
    name: 'Biópsia de próstata',
    type: 'ANATOMOPATHOLOGICAL',
    specimenDefault: 'Tecido (biópsia)',
    unit: '-',
    referenceRange: 'Ver laudo',
  },
  {
    code: 'BIOPSIA COLORRETAL',
    name: 'Biópsia colorretal',
    type: 'ANATOMOPATHOLOGICAL',
    specimenDefault: 'Tecido (biópsia)',
    unit: '-',
    referenceRange: 'Ver laudo',
  },
  {
    code: 'BIOPSIA PULMAO',
    name: 'Biópsia de pulmão',
    type: 'ANATOMOPATHOLOGICAL',
    specimenDefault: 'Tecido (biópsia)',
    unit: '-',
    referenceRange: 'Ver laudo',
  },
  {
    code: 'PAAF',
    name: 'Citologia aspirativa',
    type: 'ANATOMOPATHOLOGICAL',
    specimenDefault: 'Agulha fina (PAAF)',
    unit: '-',
    referenceRange: 'Ver laudo',
  },
  {
    code: 'AP PECA',
    name: 'Anatomopatológico de peça cirúrgica',
    type: 'ANATOMOPATHOLOGICAL',
    specimenDefault: 'Peça cirúrgica',
    unit: '-',
    referenceRange: 'Ver laudo',
  },
  {
    code: 'ER',
    name: 'Receptor de estrogênio (ER)',
    type: 'IMMUNOHISTOCHEMICAL',
    specimenDefault: 'Tecido (biópsia)',
    unit: '-',
    referenceRange: 'Ver laudo',
  },
  {
    code: 'PR',
    name: 'Receptor de progesterona (PR)',
    type: 'IMMUNOHISTOCHEMICAL',
    specimenDefault: 'Tecido (biópsia)',
    unit: '-',
    referenceRange: 'Ver laudo',
  },
  {
    code: 'HER2',
    name: 'HER2',
    type: 'IMMUNOHISTOCHEMICAL',
    specimenDefault: 'Tecido (biópsia)',
    unit: '-',
    referenceRange: '0 a 3+',
  },
  {
    code: 'KI67',
    name: 'Ki-67',
    type: 'IMMUNOHISTOCHEMICAL',
    specimenDefault: 'Tecido (biópsia)',
    unit: '%',
    referenceRange: 'Ver laudo',
  },
  {
    code: 'PDL1',
    name: 'PD-L1',
    type: 'IMMUNOHISTOCHEMICAL',
    specimenDefault: 'Tecido (biópsia)',
    unit: '%',
    referenceRange: 'CPS ou TPS conforme método',
  },
  {
    code: 'CK20',
    name: 'CK20',
    type: 'IMMUNOHISTOCHEMICAL',
    specimenDefault: 'Tecido (biópsia)',
    unit: '-',
    referenceRange: 'Ver laudo',
  },
  {
    code: 'CK7',
    name: 'CK7',
    type: 'IMMUNOHISTOCHEMICAL',
    specimenDefault: 'Tecido (biópsia)',
    unit: '-',
    referenceRange: 'Ver laudo',
  },
  {
    code: 'MAMO',
    name: 'Mamografia',
    type: 'IMAGING',
    specimenDefault: null,
    unit: '-',
    referenceRange: 'BI-RADS',
  },
  {
    code: 'US MAMA',
    name: 'Ultrassom de mama',
    type: 'IMAGING',
    specimenDefault: null,
    unit: '-',
    referenceRange: 'BI-RADS',
  },
  {
    code: 'RM MAMA',
    name: 'Ressonância de mama',
    type: 'IMAGING',
    specimenDefault: null,
    unit: '-',
    referenceRange: 'BI-RADS',
  },
  {
    code: 'TC TORAX',
    name: 'TC de tórax',
    type: 'IMAGING',
    specimenDefault: null,
    unit: '-',
    referenceRange: 'Ver laudo',
  },
  {
    code: 'TC ABDOMEN',
    name: 'TC de abdome',
    type: 'IMAGING',
    specimenDefault: null,
    unit: '-',
    referenceRange: 'Ver laudo',
  },
  {
    code: 'TC PELVE',
    name: 'TC de pelve',
    type: 'IMAGING',
    specimenDefault: null,
    unit: '-',
    referenceRange: 'Ver laudo',
  },
  {
    code: 'PETCT',
    name: 'PET-CT',
    type: 'IMAGING',
    specimenDefault: null,
    unit: '-',
    referenceRange: 'Ver laudo',
  },
  {
    code: 'RM PROSTATA',
    name: 'Ressonância de próstata',
    type: 'IMAGING',
    specimenDefault: null,
    unit: '-',
    referenceRange: 'PI-RADS',
  },
  {
    code: 'RX TORAX',
    name: 'RX de tórax',
    type: 'IMAGING',
    specimenDefault: null,
    unit: '-',
    referenceRange: 'Ver laudo',
  },
  {
    code: 'ECO',
    name: 'Ecocardiograma',
    type: 'IMAGING',
    specimenDefault: null,
    unit: '-',
    referenceRange: 'Ver laudo',
  },
  // Extras frequentes (não estão no catálogo estático mínimo) — evidenciam que a lista veio do banco após seed
  {
    code: '40301630',
    name: 'Ferritina',
    type: 'LABORATORY',
    specimenDefault: 'Sangue venoso',
    unit: 'ng/mL',
    referenceRange: '11-306 (M); 9-203 (F)',
    rolItemCode: '40301630',
  },
  {
    code: '40301400',
    name: 'Vitamina D 25-OH',
    type: 'LABORATORY',
    specimenDefault: 'Sangue venoso',
    unit: 'ng/mL',
    referenceRange: '30-100',
    rolItemCode: '40301400',
  },
  {
    code: '40302040',
    name: 'D-dímero',
    type: 'LABORATORY',
    specimenDefault: 'Sangue venoso',
    unit: 'ng/mL',
    referenceRange: '<500',
    rolItemCode: '40302040',
  },
  {
    code: '40302580',
    name: 'Proteína C reativa (PCR)',
    type: 'LABORATORY',
    specimenDefault: 'Sangue venoso',
    unit: 'mg/dL',
    referenceRange: '<0,5',
    rolItemCode: '40302580',
  },
  {
    code: '40304361',
    name: 'Troponina I',
    type: 'LABORATORY',
    specimenDefault: 'Sangue venoso',
    unit: 'ng/mL',
    referenceRange: '<0,04',
    rolItemCode: '40304361',
  },
];
