"""
Training pipeline for the Oncology Priority Ordinal Classifier (Phase 3).

**Entry point for training:** run from ``ai-service`` root::

    python -m scripts.train_model

That CLI calls ``generate_synthetic_dataset()`` below, blends optional real JSON
feedback, fits ``OncologyPriorityModel``, and logs a stratified holdout summary.
``train_and_save()`` / ``load_or_train()`` remain for programmatic or lazy startup
loads (see ``priority_model.joblib`` next to this file).

Synthetic data generation strategy:
  - Labels are generated by the SAME clinical rules engine used in production
    (not an arbitrary linear formula), ensuring clinical coherence
  - 5,000 patients generated across all risk profiles
  - Realistic correlations: fever + nadir window → high risk, etc.
  - 8% label noise to simulate clinical ambiguity in borderline cases
  - Stratified to ensure all 5 classes are well-represented
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path
from typing import Any, Dict, List

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

MODEL_PATH = Path(__file__).parent / "priority_model.joblib"

# Import from project
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from src.models.priority_model import (
    FEATURE_COLUMNS,
    DISPOSITION_TO_IDX,
    extract_features,
    priority_model,
)
from src.agent.clinical_rules import clinical_rules_engine


# ─── Synthetic patient generators ─────────────────────────────────────────────

def _make_rng(seed: int = 42) -> np.random.Generator:
    return np.random.default_rng(seed)


def _random_cancer_type(rng: np.random.Generator) -> str:
    return rng.choice([
        "breast", "lung", "colorectal", "prostate",
        "kidney", "bladder", "testicular", "lymphoma",
    ])


def _random_stage(rng: np.random.Generator, high_risk_bias: float = 0.0) -> int:
    p_base = np.array([0.20, 0.25, 0.30, 0.25])
    if high_risk_bias > 0:
        # Shift probability mass towards III/IV
        p = p_base + np.array([-0.1, -0.05, 0.05 + high_risk_bias * 0.1, 0.1 + high_risk_bias * 0.1])
        p = np.clip(p, 0, 1)
        p /= p.sum()
    else:
        p = p_base
    return int(rng.choice([1, 2, 3, 4], p=p))


def _build_synthetic_patient(
    rng: np.random.Generator,
    scenario: str = "random",
) -> Dict[str, Any]:
    """
    Build one synthetic patient context dict (matching what buildClinicalContext returns).
    scenario can be: "random", "febrile_neutropenia", "nadir_fever", "er_immediate",
                     "er_days", "advance_consult", "remote_nursing"
    """
    from datetime import datetime, timezone, timedelta

    cancer_type = _random_cancer_type(rng)
    stage = _random_stage(rng)
    age = int(rng.integers(25, 85))
    ecog = int(rng.choice([0, 1, 2, 3, 4], p=[0.20, 0.30, 0.25, 0.15, 0.10]))

    # Chemo timing
    has_chemo = bool(rng.random() > 0.3)
    days_chemo = int(rng.integers(0, 60)) if has_chemo else None

    # Vitals
    temperature = 0.0
    has_fever = 0

    # Symptoms
    pain_score = int(rng.integers(0, 11))
    nausea_score = int(rng.integers(0, 11))
    fatigue_score = int(rng.integers(0, 8))

    # Medications
    has_anticoagulant = int(rng.random() < 0.12)
    has_immunosuppressant = int(rng.random() < 0.08)
    has_corticosteroid = int(rng.random() < 0.15)

    # Comorbidities
    has_sepsis_risk = int(rng.random() < 0.10)
    has_thrombosis_risk = int(rng.random() < 0.10)

    # Override defaults by scenario
    if scenario == "febrile_neutropenia":
        temperature = float(rng.uniform(38.0, 40.5))
        has_fever = 1
        has_chemo = True
        days_chemo = int(rng.integers(0, 21))
        ecog = int(rng.choice([0, 1, 2], p=[0.3, 0.4, 0.3]))

    elif scenario == "nadir_fever":
        temperature = float(rng.uniform(38.0, 39.5))
        has_fever = 1
        has_chemo = True
        days_chemo = int(rng.integers(7, 15))

    elif scenario == "er_immediate":
        # Various ER_IMMEDIATE patterns
        t = int(rng.integers(0, 5))
        if t == 0:
            temperature = float(rng.uniform(38.0, 40.0))
            has_fever = 1
            has_chemo = True
            days_chemo = int(rng.integers(0, 21))
        elif t == 1:
            pain_score = int(rng.integers(9, 11))
        elif t == 2:
            ecog = int(rng.choice([3, 4]))
        elif t == 3:
            has_immunosuppressant = 1
            temperature = float(rng.uniform(38.0, 40.0))
            has_fever = 1
        else:
            pain_score = 10
            ecog = 3

    elif scenario == "er_days":
        t = int(rng.integers(0, 3))
        if t == 0:
            temperature = float(rng.uniform(38.0, 39.5))
            has_fever = 1
            has_chemo = False
        elif t == 1:
            pain_score = int(rng.integers(7, 9))
        else:
            nausea_score = int(rng.integers(7, 11))
            pain_score = int(rng.integers(5, 8))

    elif scenario == "advance_consult":
        pain_score = int(rng.integers(5, 7))
        ecog = int(rng.choice([1, 2]))
        fatigue_score = int(rng.integers(5, 8))

    elif scenario == "remote_nursing":
        pain_score = int(rng.integers(0, 4))
        nausea_score = int(rng.integers(0, 4))
        temperature = 0.0
        has_fever = 0
        ecog = int(rng.choice([0, 1]))

    # Build the clinical context + symptom analysis dicts
    # (matches what buildClinicalContext / SymptomAnalyzer returns)
    treatment_list = []
    if has_chemo and days_chemo is not None:
        last_date = (
            datetime.now(timezone.utc) - timedelta(days=days_chemo)
        ).isoformat()
        treatment_list.append({
            "treatmentType": "CHEMOTHERAPY",
            "isActive": True,
            "lastApplicationDate": last_date,
            "currentCycle": int(rng.integers(1, 8)),
        })

    medications = []
    for flag, name, cat in [
        (has_anticoagulant, "Varfarina", "ANTICOAGULANT"),
        (has_immunosuppressant, "Ciclosporina", "IMMUNOSUPPRESSANT"),
        (has_corticosteroid, "Prednisona", "CORTICOSTEROID"),
    ]:
        if flag:
            medications.append({
                "name": name,
                "category": cat,
                "isActive": True,
                "isAnticoagulant": cat == "ANTICOAGULANT",
                "isImmunosuppressant": cat == "IMMUNOSUPPRESSANT",
                "isCorticosteroid": cat == "CORTICOSTEROID",
                "isOpioid": False,
            })

    comorbidities = []
    if has_sepsis_risk:
        comorbidities.append({
            "type": "CHRONIC_KIDNEY_DISEASE",
            "increasesSepsisRisk": True,
            "increasesThrombosisRisk": False,
            "affectsPulmonaryReserve": False,
            "affectsRenalClearance": True,
        })
    if has_thrombosis_risk:
        comorbidities.append({
            "type": "ATRIAL_FIBRILLATION",
            "increasesSepsisRisk": False,
            "increasesThrombosisRisk": True,
            "affectsPulmonaryReserve": False,
            "affectsRenalClearance": False,
        })

    # Build detected symptoms
    detected_symptoms = []
    if has_fever:
        detected_symptoms.append({
            "name": "febre_neutropenica" if (has_chemo and days_chemo is not None and days_chemo <= 21) else "febre",
            "severity": "CRITICAL" if temperature >= 39.0 else "HIGH",
            "confidence": 0.9,
            "action": "ESCALATE_IMMEDIATELY",
        })
    if pain_score >= 7:
        detected_symptoms.append({
            "name": "dor_intensa" if pain_score >= 9 else "dor",
            "severity": "CRITICAL" if pain_score >= 9 else "HIGH",
            "confidence": 0.9,
            "action": "ESCALATE_IMMEDIATELY" if pain_score >= 9 else "ALERT_NURSING",
        })
    elif pain_score >= 4:
        detected_symptoms.append({
            "name": "dor",
            "severity": "MEDIUM",
            "confidence": 0.8,
            "action": "RECORD_AND_MONITOR",
        })
    if nausea_score >= 7:
        detected_symptoms.append({
            "name": "nausea",
            "severity": "HIGH",
            "confidence": 0.8,
            "action": "ALERT_NURSING",
        })

    clinical_context = {
        "patient": {
            "id": "synthetic",
            "name": "Synthetic",
            "cancerType": cancer_type,
            "stage": str(stage),
            "currentStage": "TREATMENT" if has_chemo else "FOLLOW_UP",
            "performanceStatus": ecog,
            "priorityScore": 50,
            "priorityCategory": "MEDIUM",
        },
        "treatments": treatment_list,
        "medications": medications,
        "comorbidities": comorbidities,
        "performanceStatusHistory": [],
    }

    symptom_analysis = {
        "detectedSymptoms": detected_symptoms,
        "overallSeverity": (
            "CRITICAL" if any(s["severity"] == "CRITICAL" for s in detected_symptoms)
            else "HIGH" if any(s["severity"] == "HIGH" for s in detected_symptoms)
            else "MEDIUM" if detected_symptoms
            else "LOW"
        ),
        "requiresEscalation": any(
            s.get("action") == "ESCALATE_IMMEDIATELY" for s in detected_symptoms
        ),
        "structuredData": {
            "scales": {
                "pain": pain_score,
                "nausea": nausea_score,
                "fatigue": fatigue_score,
                "temperature": temperature if temperature > 0 else None,
            }
        },
    }

    vitals = {"temperature": temperature if temperature > 0 else None}

    return {
        "clinical_context": clinical_context,
        "symptom_analysis": symptom_analysis,
        "vitals": vitals,
        "age": age,
    }


def _label_patient(patient_data: Dict[str, Any]) -> int:
    """
    Generate ground-truth label using the production clinical rules engine.
    This ensures the ML model learns to replicate the rules on non-obvious cases.
    """
    rules_result = clinical_rules_engine.evaluate(
        symptom_analysis=patient_data["symptom_analysis"],
        clinical_context=patient_data["clinical_context"],
        structured_vitals=patient_data.get("vitals"),
    )
    return DISPOSITION_TO_IDX[rules_result.disposition]


def generate_synthetic_dataset(n_samples: int = 5000, seed: int = 42) -> pd.DataFrame:
    """
    Generate n_samples synthetic patients with ground-truth labels from the rules engine.

    Distribution targets:
      REMOTE_NURSING:    ~40%
      SCHEDULED_CONSULT: ~25%
      ADVANCE_CONSULT:   ~15%
      ER_DAYS:           ~12%
      ER_IMMEDIATE:       ~8%
    """
    rng = _make_rng(seed)

    # Scenario weights for each class
    scenario_allocations = [
        ("remote_nursing",      int(n_samples * 0.40)),
        ("advance_consult",     int(n_samples * 0.15)),
        ("er_days",             int(n_samples * 0.12)),
        ("er_immediate",        int(n_samples * 0.08)),
        ("febrile_neutropenia", int(n_samples * 0.06)),
        ("nadir_fever",         int(n_samples * 0.04)),
        ("random",              int(n_samples * 0.15)),  # fills remaining
    ]

    all_features: List[Dict[str, Any]] = []
    all_labels: List[int] = []

    for scenario, count in scenario_allocations:
        for _ in range(count):
            patient = _build_synthetic_patient(rng, scenario)
            feats = extract_features(
                patient["clinical_context"],
                patient["symptom_analysis"],
                vitals=patient.get("vitals"),
            )
            feats["age"] = patient.get("age", feats.get("age", 60))
            label = _label_patient(patient)
            all_features.append(feats)
            all_labels.append(label)

    df = pd.DataFrame(all_features)[FEATURE_COLUMNS]

    # Add 8% label noise for borderline cases
    n_noise = int(len(all_labels) * 0.08)
    noise_idx = rng.choice(len(all_labels), size=n_noise, replace=False)
    noisy_labels = list(all_labels)
    for idx in noise_idx:
        current = noisy_labels[idx]
        # Allow ±1 class shift only (no drastic noise)
        delta = int(rng.choice([-1, 1]))
        noisy_labels[idx] = max(0, min(4, current + delta))

    df["label"] = noisy_labels

    # Log class distribution
    counts = df["label"].value_counts().sort_index()
    for cls_idx, cnt in counts.items():
        logger.info(
            f"  Class {cls_idx} ({DISPOSITION_TO_IDX.get(cls_idx, cls_idx) if isinstance(cls_idx, str) else list(DISPOSITION_TO_IDX.keys())[cls_idx] if cls_idx < len(DISPOSITION_TO_IDX) else cls_idx}): {cnt} samples"
        )

    return df


def train_and_save():
    """Train the ordinal classifier with synthetic data and save to disk."""
    logger.info("Generating synthetic training data...")
    data = generate_synthetic_dataset(n_samples=5000)

    X = data[FEATURE_COLUMNS]
    y = data["label"]

    logger.info(
        f"Training ordinal classifier on {len(X)} samples, "
        f"{y.value_counts().to_dict()} class distribution..."
    )
    metrics = priority_model.train(X, y)
    logger.info(f"Training metrics: {metrics.get('classification_report', {}).get('macro avg', {})}")

    logger.info(f"Saving model to {MODEL_PATH}")
    priority_model.save(str(MODEL_PATH))
    logger.info("Ordinal priority model trained and saved.")


def load_or_train():
    """Load saved model if available, otherwise train from scratch."""
    path_str = str(MODEL_PATH.resolve())
    if MODEL_PATH.exists():
        try:
            priority_model.load(path_str)
            logger.info("Priority model loaded from disk: %s", path_str)
            return
        except Exception as e:
            logger.warning("Failed to load saved model from %s: %s", path_str, e)

    logger.info("No saved model found, training from synthetic data...")
    train_and_save()
